name: Minecraft Bot 24/7
on:
  push:
    branches: [ main ]
  schedule:
    - cron: '*/15 * * * *' 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # تحديث لنسخة أحدث
      - name: Setup Node.js
        uses: actions/setup-node@v4 # تحديث لنسخة أحدث
        with:
          node-version: '22' # قمنا بتغيير الإصدار هنا إلى 22
      - name: Install Dependencies
        run: npm install mineflayer
      - name: Run Bot
        run: node index.js
        timeout-minutes: 350
